dataset_type: voc  #voc or raw
train_folder: C:\Users\F36RB01\Documents\master\TFM\repos\pascalRaw_split\train
val_folder: C:\Users\F36RB01\Documents\master\TFM\repos\pascalRaw_split\val
annotations_file: null

isp:
  config_file: configs/tuning_vocDataset.yaml

detector:
  verbose: False
  show_img: True
  save_img: False
  output_folder: processed_imgs\detections

optimizer:
  optimizer_type: null #cma or bayesian
  normalization: True
  bounds:
    gac:
      gain: [10, 4096]
      gamma: [0.2, 3.]

    bcc:
      brightness_offset: [0, 500]
      contrast_gain: [0, 1000]                  # x256

  init:
    gac:
      gain: 256
      gamma: 0.45

    bcc:
      brightness_offset: 0
      contrast_gain: 300