dataset_type: voc  #voc or raw
train_folder: C:\Users\F36RB01\Documents\master\TFM\repos\raw_dataset.v4i.voc\train
val_folder: C:\Users\F36RB01\Documents\master\TFM\repos\raw_dataset.v4i.voc\valid
annotations_file: null

isp:
  config_file: configs/CMAOpt_tuning_rawDataset.yaml
  multithread: True

detector:
  verbose: False
  show_img: False
  save_img: True
  output_folder: processed_imgs/test/
  classes: [car, person, motorbike, truck] #[car, person, motorbike, truck]
  show_gt: False
  ficosa_model: False
  model_path: models/best.onnx

optimizer:
  optimizer_type: inference #cma, bayesian or inference
  normalization: True
  bounds:
    gac:
      gain: [10, 4096]
      gamma: [0.2, 3.]

    bcc:
      brightness_offset: [0, 500]
      contrast_gain: [0, 1000]                  # x256

    ceh:
      tiles: [ [2, 100], [2, 150] ]
      clip_limit: [0.02, 100.0]

  init:
    gac:
      gain: 256
      gamma: 0.45

    bcc:
      brightness_offset: 0
      contrast_gain: 300

    ceh:
      tiles: [2, 6]
      clip_limit: 0.02